# Generated by Django 6.0.4 on 2026-05-04 13:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloader", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoformat",
            name="download_instance",
        ),
        migrations.CreateModel(
            name="MediaDownload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("media_url", models.URLField(max_length=500)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("youtube", "YouTube"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("tiktok", "TikTok"),
                            ("pinterest", "Pinterest"),
                            ("twitter", "Twitter/X"),
                            ("reddit", "Reddit"),
                            ("vimeo", "Vimeo"),
                            ("dailymotion", "Dailymotion"),
                            ("twitch", "Twitch"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("post", "Post"),
                        ],
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("thumbnail", models.URLField(blank=True)),
                ("duration", models.CharField(blank=True, max_length=20)),
                ("uploader", models.CharField(blank=True, max_length=200)),
                ("file_path", models.CharField(blank=True, max_length=500)),
                ("file_size", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resolution", models.CharField(max_length=20)),
                ("format_id", models.CharField(max_length=50)),
                ("filesize", models.CharField(blank=True, max_length=50)),
                ("extension", models.CharField(max_length=10)),
                (
                    "media_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                            ("post", "Post"),
                        ],
                        default="video",
                        max_length=10,
                    ),
                ),
                ("download_url", models.URLField(blank=True)),
                (
                    "download_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formats",
                        to="downloader.mediadownload",
                    ),
                ),
            ],
            options={
                "ordering": ["-resolution"],
            },
        ),
        migrations.DeleteModel(
            name="VideoDownload",
        ),
        migrations.DeleteModel(
            name="VideoFormat",
        ),
    ]
