# Generated by Django 6.0.4 on 2026-05-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "downloader",
            "0002_remove_videoformat_download_instance_mediadownload_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediadownload",
            name="file_path",
            field=models.FileField(blank=True, null=True, upload_to="downloads/"),
        ),
    ]
