# Generated by Django 6.0.4 on 2026-05-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("downloader", "0003_alter_mediadownload_file_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediadownload",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="mediaformat",
            name="download_url",
        ),
    ]
