# Generated by Django 6.0.4 on 2026-05-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloader", "0004_remove_mediadownload_file_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediadownload",
            name="country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="mediadownload",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mediadownload",
            name="referrer",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="mediadownload",
            name="user_agent",
            field=models.TextField(blank=True),
        ),
    ]
