# Generated by Django 6.0.4 on 2026-05-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("downloader", "0005_add_tracking_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediadownload",
            name="country",
        ),
    ]
