# Generated by Django 6.0.4 on 2026-05-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("downloader", "0006_remove_country_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediadownload",
            name="referrer",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
